# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  # name of the builder
  entityPropsBuilder:
    import: "package:flora_orm/builder.dart"
    builder_factories: ["entityPropsBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      flora_orm|entityPropsBuilder:
        generate_for:
          - lib/*.entity.dart
          - lib/**/*.entity.dart