# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  # name of the builder
  db_columns:
    import: "package:tatlacas_sqflite_storage/builder.dart"
    builder_factories: ["dbColumnsBuilder"]
    build_extensions: {".dart": [".cols.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      tatlacas_sqflite_storage|db_columns:
        generate_for:
          - lib/**/*.entity.dart