name: flora_orm
version: 1.0.1
publish_to: none
description: sqflite storage
environment: 
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.16.0'
dependencies: 
  analyzer: ^6.2.0
  build: ^2.4.1
  build_config: ^1.1.1
  equatable: ^2.0.3
  flutter: 
    sdk: flutter
  flutter_lints: ^4.0.0
  meta: ^1.7.0
  path: any
  path_provider: ^2.0.11
  pubspec_dependency_sorter: ^1.0.4
  shared_preferences: ^2.0.15
  source_gen: ^1.4.0
  sqflite: ^2.0.3
  sqflite_common: any
  sqflite_common_ffi: ^2.1.1+1
  uuid: ^4.2.2
dev_dependencies: 
  build_runner: ^2.4.9
  flutter_test: 
    sdk: flutter
