name: tatlacas_sqflite_storage
description: sqflite storage
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.1.0
  sqflite: ^2.0.1
  uuid: ^3.0.5
  path_provider: ^2.0.8
  equatable: ^2.0.3
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter