name: flora_orm
repository: https://github.com/tatlacas-com/flora_orm/tree/main
issue_tracker: https://github.com/tatlacas-com/flora_orm/issues
description: Flutter plugin for ORM in front of storage like sqflite and shared_preferences
version: 1.0.9

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:

topics:
  - sql
  - database
  - orm
  - storage
  - persistence

environment: 
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.16.0'

dependencies: 
  analyzer: ^6.7.0
  build: ^2.4.1
  build_config: ^1.1.1
  equatable: ^2.0.3
  flutter: 
    sdk: flutter
  flutter_lints: ^5.0.0
  meta: ^1.7.0
  path: ^1.9.0
  path_provider: ^2.0.11
  pubspec_dependency_sorter: ^1.0.4
  shared_preferences: ^2.0.15
  source_gen: ^1.4.0
  sqflite: ^2.0.3
  sqflite_common: ^2.5.4+5
  sqflite_common_ffi: ^2.1.1+1
  uuid: ^4.2.2

dev_dependencies: 
  build_runner: ^2.4.9
  flutter_test: 
    sdk: flutter
