name: tatlacas_sqflite_storage
description: sqflite storage
version: 1.0.1
publish_to: none
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.1.1+1
  sqflite: ^2.0.3
  uuid: ^4.2.2
  path_provider: ^2.0.11
  equatable: ^2.0.3
  meta: ^1.7.0
  shared_preferences: ^2.0.15
  source_gen: ^1.4.0
  build: ^2.4.1
  analyzer: ^6.2.0
  worker_manager: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter